/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PxIndexRouteImport } from './routes/px/index'
import { Route as PxNewRouteImport } from './routes/px/new'
import { Route as PxPatientIdRouteImport } from './routes/px/$patientId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PxIndexRoute = PxIndexRouteImport.update({
  id: '/px/',
  path: '/px/',
  getParentRoute: () => rootRouteImport,
} as any)
const PxNewRoute = PxNewRouteImport.update({
  id: '/px/new',
  path: '/px/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PxPatientIdRoute = PxPatientIdRouteImport.update({
  id: '/px/$patientId',
  path: '/px/$patientId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/px/$patientId': typeof PxPatientIdRoute
  '/px/new': typeof PxNewRoute
  '/px/': typeof PxIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/px/$patientId': typeof PxPatientIdRoute
  '/px/new': typeof PxNewRoute
  '/px': typeof PxIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/px/$patientId': typeof PxPatientIdRoute
  '/px/new': typeof PxNewRoute
  '/px/': typeof PxIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/px/$patientId' | '/px/new' | '/px/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/px/$patientId' | '/px/new' | '/px'
  id: '__root__' | '/' | '/px/$patientId' | '/px/new' | '/px/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PxPatientIdRoute: typeof PxPatientIdRoute
  PxNewRoute: typeof PxNewRoute
  PxIndexRoute: typeof PxIndexRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/px/': {
      id: '/px/'
      path: '/px'
      fullPath: '/px/'
      preLoaderRoute: typeof PxIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/px/new': {
      id: '/px/new'
      path: '/px/new'
      fullPath: '/px/new'
      preLoaderRoute: typeof PxNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/px/$patientId': {
      id: '/px/$patientId'
      path: '/px/$patientId'
      fullPath: '/px/$patientId'
      preLoaderRoute: typeof PxPatientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PxPatientIdRoute: PxPatientIdRoute,
  PxNewRoute: PxNewRoute,
  PxIndexRoute: PxIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
