/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PatientsIndexRouteImport } from './routes/patients/index'
import { Route as PatientsNewRouteImport } from './routes/patients/new'
import { Route as PatientsPatientIdRouteImport } from './routes/patients/$patientId'
import { Route as AccidentsAccidentIdRouteImport } from './routes/accidents/$accidentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsIndexRoute = PatientsIndexRouteImport.update({
  id: '/patients/',
  path: '/patients/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsNewRoute = PatientsNewRouteImport.update({
  id: '/patients/new',
  path: '/patients/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsPatientIdRoute = PatientsPatientIdRouteImport.update({
  id: '/patients/$patientId',
  path: '/patients/$patientId',
  getParentRoute: () => rootRouteImport,
} as any)
const AccidentsAccidentIdRoute = AccidentsAccidentIdRouteImport.update({
  id: '/accidents/$accidentId',
  path: '/accidents/$accidentId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accidents/$accidentId': typeof AccidentsAccidentIdRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
  '/patients/new': typeof PatientsNewRoute
  '/patients/': typeof PatientsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accidents/$accidentId': typeof AccidentsAccidentIdRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
  '/patients/new': typeof PatientsNewRoute
  '/patients': typeof PatientsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accidents/$accidentId': typeof AccidentsAccidentIdRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
  '/patients/new': typeof PatientsNewRoute
  '/patients/': typeof PatientsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accidents/$accidentId'
    | '/patients/$patientId'
    | '/patients/new'
    | '/patients/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accidents/$accidentId'
    | '/patients/$patientId'
    | '/patients/new'
    | '/patients'
  id:
    | '__root__'
    | '/'
    | '/accidents/$accidentId'
    | '/patients/$patientId'
    | '/patients/new'
    | '/patients/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccidentsAccidentIdRoute: typeof AccidentsAccidentIdRoute
  PatientsPatientIdRoute: typeof PatientsPatientIdRoute
  PatientsNewRoute: typeof PatientsNewRoute
  PatientsIndexRoute: typeof PatientsIndexRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/': {
      id: '/patients/'
      path: '/patients'
      fullPath: '/patients/'
      preLoaderRoute: typeof PatientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/new': {
      id: '/patients/new'
      path: '/patients/new'
      fullPath: '/patients/new'
      preLoaderRoute: typeof PatientsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/$patientId': {
      id: '/patients/$patientId'
      path: '/patients/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof PatientsPatientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accidents/$accidentId': {
      id: '/accidents/$accidentId'
      path: '/accidents/$accidentId'
      fullPath: '/accidents/$accidentId'
      preLoaderRoute: typeof AccidentsAccidentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccidentsAccidentIdRoute: AccidentsAccidentIdRoute,
  PatientsPatientIdRoute: PatientsPatientIdRoute,
  PatientsNewRoute: PatientsNewRoute,
  PatientsIndexRoute: PatientsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
